### ISSUE TITLE
sp certificate and key files are completely ignored

### ISSUE THREAD

**Issue by gantsevdenis** [winstonhong/Shibboleth-SAML-IdP-and-SP#5]
Unless I don't understand something (which is likely), those files are bogus: I was able to successfully launch service provider container **and fully authenticate** without them (I removed them completely to see what type of error would happen)

It's quite surprising, and I am not sure how to turn "real" authentication on..

**Comment by winstonhong** [comment]
SAML IdP and SAML SP need to exchange their certificate/key through their metadata file in order to perform the SAML authentication and identity federation.

(I) For SAML IdP

You need to put the SAML SP metadata into the folder "shibboleth-idp-dockerized/ext-conf/metadata/"

Note that 

(1) The SAML SP metadata includes SP certificate/key.

(2) All the SP applications in the folder "shibboleth-idp-dockerized/ext-conf/metadata/" has been validated.

(II) For SAML SP

SAML IdP metadata has to be included in the folder "shibboleth-sp-testapp/shibboleth-sp/".

(III) To demonstrate the SAML authentication failure,

(1) You can remove SAML SP metadata "sp-example-org.xml" from the folder "shibboleth-idp-dockerized/ext-conf/metadata/"

or 

(2) You can remove SAML IdP metadata "idp-metadata.xml" from the folder "shibboleth-sp-testapp/shibboleth-sp/"

Then rebuild and re-run the Docker image of both SAML IdP and SAML SP.

**Comment by gantsevdenis** [comment]
Hi  winstonhong 
Thank you for detailed answer!

I was able to correctly use `shibboleth-idp` with my own test `service provider`.
However, when using `shibboleth-sp` removing `sp-example-org.xml` does not make authentication failure. I think `shibboleth-sp` uses internally `sp-encrypt-cert.pem` and `sp-encrypt-key.pem` in `/etc/shibboleth`

It does not matter for me, because I can use my own service provider correctly, but it's just suprising
